"""empty message

Revision ID: 3e40c40eec3f
Revises: 
Create Date: 2020-05-07 10:32:58.935050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e40c40eec3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UserID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Password', sa.String(length=125), nullable=False),
    sa.Column('Sex', sa.String(length=10), nullable=True),
    sa.Column('Username', sa.String(length=125), nullable=True),
    sa.Column('DormitoryID', sa.String(length=125), nullable=True),
    sa.Column('Phone', sa.String(length=125), nullable=True),
    sa.Column('Email', sa.String(length=125), nullable=True),
    sa.Column('CallMethod', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
