"""empty message

Revision ID: af84eba42293
Revises: 3e40c40eec3f
Create Date: 2020-05-08 09:48:45.497902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af84eba42293'
down_revision = '3e40c40eec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitory',
    sa.Column('dormitoryid', sa.String(length=125), nullable=True),
    sa.Column('dormitoryname', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('dormitoryid')
    )
    op.create_table('envirment',
    sa.Column('dormitoryid', sa.String(length=125), nullable=True),
    sa.Column('temperature', sa.Float(precision=10), nullable=False),
    sa.Column('humidity', sa.Float(precision=10), nullable=False),
    sa.Column('time', sa.TIMESTAMP(timezone=20), nullable=False),
    sa.PrimaryKeyConstraint('dormitoryid')
    )
    op.create_table('remain',
    sa.Column('remindid', sa.String(length=125), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('remindid')
    )
    op.create_table('remain_log',
    sa.Column('remindid', sa.String(length=125), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('remindid', 'time')
    )
    op.create_table('vedio',
    sa.Column('vedioid', sa.String(length=125), nullable=True),
    sa.Column('dormitoryid', sa.String(length=125), nullable=True),
    sa.Column('vediobegin', sa.TIMESTAMP(timezone=20), nullable=True),
    sa.Column('vedioend', sa.TIMESTAMP(timezone=20), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dormitoryid'], ['dormitory.dormitoryid'], ),
    sa.PrimaryKeyConstraint('vedioid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vedio')
    op.drop_table('remain_log')
    op.drop_table('remain')
    op.drop_table('envirment')
    op.drop_table('dormitory')
    # ### end Alembic commands ###
